/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.NhanVienDAO;
import bean.DanhMuc;
import controll.chuyenManHinh;
import java.awt.Color;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nguyen Bach Long
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        Pojo.NhanVien nv = NhanVienDAO.LayNhanVienTheoMa(DangNhap.idTaiKhoang);
        txtQuyen.setText(nv.quyen + ": ");
        txtTaiKhoan.setText(nv.hoTen);
        chuyenManHinh contro = new chuyenManHinh(jpnView);
        contro.setView(tab_BanHang, jLbBangHang);
        List<DanhMuc> listItem = new ArrayList<>();
        if(nv.quyen.equals("Admin"))
        {
            listItem.add(new DanhMuc("BanHang", tab_BanHang, jLbBangHang));
            listItem.add(new DanhMuc("ThongKe", tab_HoaDon, jLbHoaDon));
            listItem.add(new DanhMuc("SanPham", tab_SanPham, jblSanham));
            listItem.add(new DanhMuc("NhanVien", tab_NhanVien, jblNhanVien));
            listItem.add(new DanhMuc("KhachHang", tab_KhachHang, jblKhachHang));
            listItem.add(new DanhMuc("NhapHang", tab_NhapHang, jblNhapHang));
            listItem.add(new DanhMuc("NhaCungCap", tab_NCC, jblNCC));
        }
        else
        {
            listItem.add(new DanhMuc("BanHang", tab_BanHang, jLbBangHang));
            listItem.add(new DanhMuc("ThongKe", tab_HoaDon, jLbHoaDon));
            listItem.add(new DanhMuc("KhachHang", tab_KhachHang, jblKhachHang));
            listItem.add(new DanhMuc("NhapHang", tab_NhapHang, jblNhapHang));
            tab_SanPham.setBackground(Color.red);
            tab_NhanVien.setBackground(Color.red);
            tab_NCC.setBackground(Color.red);
            
        }
      

        contro.setEvent(listItem);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMenu = new javax.swing.JPanel();
        tab_BanHang = new javax.swing.JPanel();
        jLbBangHang = new javax.swing.JLabel();
        tab_HoaDon = new javax.swing.JPanel();
        jLbHoaDon = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JLabel();
        txtQuyen = new javax.swing.JLabel();
        tab_SanPham = new javax.swing.JPanel();
        jblSanham = new javax.swing.JLabel();
        tab_NhanVien = new javax.swing.JPanel();
        jblNhanVien = new javax.swing.JLabel();
        tab_KhachHang = new javax.swing.JPanel();
        jblKhachHang = new javax.swing.JLabel();
        btnTTNV = new javax.swing.JButton();
        tab_NCC = new javax.swing.JPanel();
        jblNCC = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tab_NhapHang = new javax.swing.JPanel();
        jblNhapHang = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(0, 204, 204));

        tab_BanHang.setBackground(new java.awt.Color(76, 175, 80));
        tab_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_BanHangMouseClicked(evt);
            }
        });

        jLbBangHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbBangHang.setForeground(new java.awt.Color(255, 255, 255));
        jLbBangHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-product-30.png"))); // NOI18N
        jLbBangHang.setText("BÁN HÀNG");

        javax.swing.GroupLayout tab_BanHangLayout = new javax.swing.GroupLayout(tab_BanHang);
        tab_BanHang.setLayout(tab_BanHangLayout);
        tab_BanHangLayout.setHorizontalGroup(
            tab_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_BanHangLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLbBangHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab_BanHangLayout.setVerticalGroup(
            tab_BanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbBangHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        tab_HoaDon.setBackground(new java.awt.Color(76, 175, 80));
        tab_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_HoaDonMouseClicked(evt);
            }
        });

        jLbHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jLbHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-bill-30.png"))); // NOI18N
        jLbHoaDon.setText("THỐNG KÊ");

        javax.swing.GroupLayout tab_HoaDonLayout = new javax.swing.GroupLayout(tab_HoaDon);
        tab_HoaDon.setLayout(tab_HoaDonLayout);
        tab_HoaDonLayout.setHorizontalGroup(
            tab_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_HoaDonLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLbHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab_HoaDonLayout.setVerticalGroup(
            tab_HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLbHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        txtTaiKhoan.setText("NuLL");

        txtQuyen.setBackground(new java.awt.Color(255, 255, 255));
        txtQuyen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuyen.setForeground(new java.awt.Color(255, 255, 255));
        txtQuyen.setText("NULL :");

        tab_SanPham.setBackground(new java.awt.Color(76, 175, 80));
        tab_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_SanPhamMouseClicked(evt);
            }
        });

        jblSanham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblSanham.setForeground(new java.awt.Color(255, 255, 255));
        jblSanham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-product-30 (1).png"))); // NOI18N
        jblSanham.setText("SẢN PHẨM");

        javax.swing.GroupLayout tab_SanPhamLayout = new javax.swing.GroupLayout(tab_SanPham);
        tab_SanPham.setLayout(tab_SanPhamLayout);
        tab_SanPhamLayout.setHorizontalGroup(
            tab_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_SanPhamLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jblSanham, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab_SanPhamLayout.setVerticalGroup(
            tab_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblSanham, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab_NhanVien.setBackground(new java.awt.Color(76, 175, 80));
        tab_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_NhanVienMouseClicked(evt);
            }
        });

        jblNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jblNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-bill-30.png"))); // NOI18N
        jblNhanVien.setText("NHÂN VIÊN");

        javax.swing.GroupLayout tab_NhanVienLayout = new javax.swing.GroupLayout(tab_NhanVien);
        tab_NhanVien.setLayout(tab_NhanVienLayout);
        tab_NhanVienLayout.setHorizontalGroup(
            tab_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_NhanVienLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jblNhanVien)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        tab_NhanVienLayout.setVerticalGroup(
            tab_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        tab_KhachHang.setBackground(new java.awt.Color(76, 175, 80));
        tab_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_KhachHangMouseClicked(evt);
            }
        });

        jblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jblKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-30.png"))); // NOI18N
        jblKhachHang.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout tab_KhachHangLayout = new javax.swing.GroupLayout(tab_KhachHang);
        tab_KhachHang.setLayout(tab_KhachHangLayout);
        tab_KhachHangLayout.setHorizontalGroup(
            tab_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_KhachHangLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jblKhachHang)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        tab_KhachHangLayout.setVerticalGroup(
            tab_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        btnTTNV.setText("Thông tin nhân viên");
        btnTTNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTNVActionPerformed(evt);
            }
        });

        tab_NCC.setBackground(new java.awt.Color(76, 175, 80));
        tab_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_NCCMouseClicked(evt);
            }
        });

        jblNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNCC.setForeground(new java.awt.Color(255, 255, 255));
        jblNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-user-30.png"))); // NOI18N
        jblNCC.setText("NHÀ CUNG CẤP");

        javax.swing.GroupLayout tab_NCCLayout = new javax.swing.GroupLayout(tab_NCC);
        tab_NCC.setLayout(tab_NCCLayout);
        tab_NCCLayout.setHorizontalGroup(
            tab_NCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_NCCLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jblNCC)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        tab_NCCLayout.setVerticalGroup(
            tab_NCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tab_NhapHang.setBackground(new java.awt.Color(76, 175, 80));
        tab_NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_NhapHangMouseClicked(evt);
            }
        });

        jblNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNhapHang.setForeground(new java.awt.Color(255, 255, 255));
        jblNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-bill-30.png"))); // NOI18N
        jblNhapHang.setText("NHẬP HÀNG");

        javax.swing.GroupLayout tab_NhapHangLayout = new javax.swing.GroupLayout(tab_NhapHang);
        tab_NhapHang.setLayout(tab_NhapHangLayout);
        tab_NhapHangLayout.setHorizontalGroup(
            tab_NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_NhapHangLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jblNhapHang)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        tab_NhapHangLayout.setVerticalGroup(
            tab_NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab_BanHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTTNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnMenuLayout.createSequentialGroup()
                        .addComponent(txtQuyen)
                        .addGap(18, 18, 18)
                        .addComponent(txtTaiKhoan)))
                .addContainerGap(280, Short.MAX_VALUE))
            .addComponent(tab_NCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tab_KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
            .addComponent(tab_NhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaiKhoan)
                    .addComponent(txtQuyen))
                .addGap(18, 18, 18)
                .addComponent(btnTTNV)
                .addGap(115, 115, 115)
                .addComponent(tab_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab_NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_SanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_SanPhamMouseClicked

    private void tab_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_HoaDonMouseClicked

    }//GEN-LAST:event_tab_HoaDonMouseClicked

    private void tab_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_BanHangMouseClicked

    }//GEN-LAST:event_tab_BanHangMouseClicked

    private void tab_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_NhanVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_NhanVienMouseClicked

    private void tab_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_KhachHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_KhachHangMouseClicked

    private void btnTTNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTNVActionPerformed
        try {
            FormChiTietNhanVienChoTKNhanVien f = new FormChiTietNhanVienChoTKNhanVien();
            f.setVisible(true);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTTNVActionPerformed

    private void tab_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_NCCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_NCCMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
       DangNhap f = new DangNhap();
       f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tab_NhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_NhapHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tab_NhapHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTTNV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLbBangHang;
    private javax.swing.JLabel jLbHoaDon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblKhachHang;
    private javax.swing.JLabel jblNCC;
    private javax.swing.JLabel jblNhanVien;
    private javax.swing.JLabel jblNhapHang;
    private javax.swing.JLabel jblSanham;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel tab_BanHang;
    private javax.swing.JPanel tab_HoaDon;
    private javax.swing.JPanel tab_KhachHang;
    private javax.swing.JPanel tab_NCC;
    private javax.swing.JPanel tab_NhanVien;
    private javax.swing.JPanel tab_NhapHang;
    private javax.swing.JPanel tab_SanPham;
    private javax.swing.JLabel txtQuyen;
    private javax.swing.JLabel txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
