/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.NhaCungCapDAO;
import DAO.SanPhamDAO;
import Pojo.NhaCungCap;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Bach Long
 */
public class QLSANPHAM extends javax.swing.JPanel {

    /**
     * Creates new form QLSANPHAM
     */
    DefaultTableModel dtb = new DefaultTableModel();
    boolean chooseImg = false;
    String srcAnh = "./src/Images/";
    String anh;
    String gia;
    public QLSANPHAM() {
        initComponents();
        String [] tieuDe={"Mã sản phẩm","Loại sản phẩm","Tên sản phẩm","Màu sắc","Đơn giá", "Số Lượng","Nhà cung cấp","Trạng thái"};
        dtb.setColumnIdentifiers(tieuDe);
        tb_sanpham.setModel(dtb);
        hienThi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_maSP = new javax.swing.JTextField();
        txt_tenSP = new javax.swing.JTextField();
        txt_mau = new javax.swing.JTextField();
        txt_donGia = new javax.swing.JTextField();
        btn_themSP = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_chiTietSP = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        lb_hinh = new javax.swing.JLabel();
        btn_loadlai = new javax.swing.JButton();
        btn_themAnh1 = new javax.swing.JButton();
        cbx_loaiSP1 = new javax.swing.JComboBox<>();
        cbx_ncc1 = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        cbx_loaiSP = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        cbx_ncc = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        cbx_tt = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        cbx_giaTien = new javax.swing.JComboBox<>();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_sanpham = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txt_maSP1 = new javax.swing.JTextField();
        txt_tenLoai1 = new javax.swing.JTextField();
        txt_tenSP1 = new javax.swing.JTextField();
        txt_donGia1 = new javax.swing.JTextField();
        txt_ncc1 = new javax.swing.JTextField();
        txt_mau1 = new javax.swing.JTextField();
        btn_themAnh = new javax.swing.JButton();
        btn_luu1 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        lb_hinhAnhSanPham = new javax.swing.JLabel();
        cbx_tt1 = new javax.swing.JComboBox<>();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));

        jLabel2.setText("Mã sản phẩm");

        jLabel10.setText("Tên loại");

        jLabel20.setText("Tên sản phẩm");

        jLabel27.setText("Màu");

        jLabel34.setText("Nhà cung cấp");

        jLabel35.setText("Đơn giá");

        txt_maSP.setEnabled(false);

        txt_tenSP.setEnabled(false);

        txt_mau.setEnabled(false);

        txt_donGia.setEnabled(false);

        btn_themSP.setBackground(new java.awt.Color(255, 204, 51));
        btn_themSP.setText("Thêm sản phẩm");
        btn_themSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themSPMouseClicked(evt);
            }
        });
        btn_themSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themSPActionPerformed(evt);
            }
        });

        btn_luu.setBackground(new java.awt.Color(255, 204, 51));
        btn_luu.setText("Lưu");
        btn_luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luuMouseClicked(evt);
            }
        });
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_chiTietSP.setBackground(new java.awt.Color(255, 204, 51));
        btn_chiTietSP.setText("Chi tiết sản phẩm");
        btn_chiTietSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_chiTietSPMouseClicked(evt);
            }
        });

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_hinh, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_hinh, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_loadlai.setBackground(new java.awt.Color(255, 204, 51));
        btn_loadlai.setText("Load lại");
        btn_loadlai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loadlaiMouseClicked(evt);
            }
        });

        btn_themAnh1.setText("Chọn ảnh");
        btn_themAnh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themAnh1MouseClicked(evt);
            }
        });

        cbx_loaiSP1.setEnabled(false);
        cbx_loaiSP1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_loaiSP1ItemStateChanged(evt);
            }
        });

        cbx_ncc1.setEnabled(false);
        cbx_ncc1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_ncc1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_maSP, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(cbx_loaiSP1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_mau, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel16Layout.createSequentialGroup()
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel16Layout.createSequentialGroup()
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbx_ncc1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(btn_themAnh1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chiTietSP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_loadlai, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themSP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel34)
                    .addComponent(cbx_loaiSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_ncc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel20)
                    .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_themAnh1)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(btn_themSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_chiTietSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_loadlai))
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc sản phẩm"));

        jLabel36.setText("Loại sản phẩm:");

        cbx_loaiSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_loaiSPItemStateChanged(evt);
            }
        });

        jLabel37.setText("Nhà cung cấp:");

        cbx_ncc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_nccItemStateChanged(evt);
            }
        });

        jLabel38.setText("Trạng thái:");

        cbx_tt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_ttItemStateChanged(evt);
            }
        });

        jLabel39.setText("Tìm kiếm:");

        btn_timkiem.setText("Tìm");
        btn_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timkiemMouseClicked(evt);
            }
        });

        jLabel40.setText("Giá:");

        cbx_giaTien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0đ - 100.000đ", "100.000đ - 500.000đ", "500.000đ - 1.000.000đ", "< 1.000.000đ" }));
        cbx_giaTien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_giaTienItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_loaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel36)))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbx_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_giaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel37)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel38)
                        .addGap(102, 102, 102)
                        .addComponent(jLabel40)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel39)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_loaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem)
                    .addComponent(cbx_giaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));

        tb_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_sanpham.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tb_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sanphamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_sanpham);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông Tin Sản Phẩm", jPanel1);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 0, 0));
        jLabel41.setText("THÔNG TIN CHI TIẾT SẢN PHẨM");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel42.setText("Mã sản phẩm");

        jLabel43.setText("Tên loại");

        jLabel44.setText("Tên sản phẩm");

        jLabel45.setText("Đơn giá");

        jLabel46.setText("Nhà cung cấp");

        jLabel47.setText("Màu");

        txt_maSP1.setEnabled(false);

        txt_tenLoai1.setEnabled(false);

        txt_ncc1.setEnabled(false);

        btn_themAnh.setText("Chọn ảnh");
        btn_themAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themAnhMouseClicked(evt);
            }
        });

        btn_luu1.setText("LƯU THAY ĐỔI");
        btn_luu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luu1MouseClicked(evt);
            }
        });
        btn_luu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu1ActionPerformed(evt);
            }
        });

        jLabel48.setText("Trạng thái");

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_hinhAnhSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_hinhAnhSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbx_tt1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_tt1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_donGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ncc1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mau1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_maSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 585, Short.MAX_VALUE))
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btn_luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(btn_themAnh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_maSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tenLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txt_donGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ncc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(txt_mau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbx_tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_themAnh)
                .addGap(18, 18, 18)
                .addComponent(btn_luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chi Tiết Sản Phẩm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themSPMouseClicked
        
        txt_maSP.setText("");
        txt_tenSP.setText("");
        txt_mau.setText("");
        txt_tenSP.requestFocus();
        txt_tenSP.enable(true);
        txt_mau.enable(true);
        txt_donGia.enable(true);
        txt_donGia.requestFocus();
        cbx_loaiSP1.setEnabled(true);
        txt_mau.requestFocus();
        cbx_ncc1.setEnabled(true);
    }//GEN-LAST:event_btn_themSPMouseClicked

    private void btn_themSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_themSPActionPerformed

    private void btn_luuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luuMouseClicked
        if(txt_tenSP.getText().isEmpty()||txt_mau.getText().isEmpty())
        {
            JOptionPane.showConfirmDialog(null, "Vui lòng nhập đầy đủ thông tin sản phẩm muốn thêm!!!", "Thông báo!", JOptionPane.DEFAULT_OPTION);
        }
        else{
            Object nccSelected = cbx_ncc1.getSelectedItem();
            String tenncc = nccSelected.toString();
            Object loaiSelected = cbx_loaiSP1.getSelectedItem();
            String tenloai = loaiSelected.toString();
            NhaCungCap ncc = NhaCungCapDAO.TimMaNCCTheoTenNCC(tenncc);
            String mancc = String.valueOf(ncc.getMaNCC());
            Pojo.SanPham sp = SanPhamDAO.TimMaloaiTheoTenLoai(tenloai);
            String maloai = String.valueOf(sp.getMaLoai());
            boolean kq = SanPhamDAO.kiemTraSanPham(txt_tenSP.getText(),  mancc, txt_mau.getText(), maloai);

            if(kq)
            {
                JOptionPane.showConfirmDialog(null, "Đã có mặt hàng này trong cửa hàng !!!", "Thông báo!", JOptionPane.DEFAULT_OPTION);
            }
            else{
                String src=srcAnh;
                if(SanPhamDAO.themSanPham(txt_tenSP.getText(), maloai, mancc, txt_mau.getText(),src))
                {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công");
                    hienThi();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!!!");
                }
            }
            txt_tenSP.setEditable(false);
            txt_mau.setEditable(false);
            cbx_loaiSP1.setEnabled(false);
            cbx_ncc1.setEnabled(false);
        }
    }//GEN-LAST:event_btn_luuMouseClicked

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_chiTietSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chiTietSPMouseClicked
        // TODO add your handling code here:
        Pojo.SanPham sp = SanPhamDAO.loadSP(txt_maSP.getText());
        String ma = String.valueOf(sp.getMaSP());
        String gia = String.valueOf(sp.getDonGia());
        txt_maSP1.setText(ma);
        txt_tenSP1.setText(sp.getTenSP());
        txt_tenLoai1.setText(sp.getTenLoai());
        txt_donGia1.setText(gia);
        txt_mau1.setText(sp.getMau());
        txt_ncc1.setText(sp.getTenNCC());
        lb_hinhAnhSanPham.setIcon(ResizeImage1(sp.getHinh()));
        anh = sp.getHinh();
        cbx_tt1.removeAllItems();
        hienThiComboBoxChiTietSP(sp.getTrangThai());
        
    }//GEN-LAST:event_btn_chiTietSPMouseClicked

    private void btn_loadlaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loadlaiMouseClicked
        // TODO add your handling code here:
        hienThi();
    }//GEN-LAST:event_btn_loadlaiMouseClicked

    private void btn_themAnh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themAnh1MouseClicked
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser(System.getProperty("user.dir") + "./Images/");
            f.setDialogTitle("Chọn Ảnh");
            f.showOpenDialog(null);
            File fileAnh = f.getSelectedFile();
            if (fileAnh != null) {
                if (fileAnh.getAbsolutePath().contains("./Images/")) {
                    srcAnh = fileAnh.getName();
                } else {
                    File dirAnh = new File("./Images/");
                    srcAnh = dirAnh.toURI().relativize(fileAnh.getCanonicalFile().toURI()).getPath();
                }
                // Nối đường dẫn tương đối đến thư mục Images/ vào phía trước tên file ảnh.
                srcAnh = "./Images/" + srcAnh;
                lb_hinh.setIcon(ResizeImage(srcAnh));
                chooseImg = true;
            }

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Đã xảy ra sự cố! Không thể tải ảnh lên", "Thông báo!", JOptionPane.DEFAULT_OPTION);
            return;
        }
    }//GEN-LAST:event_btn_themAnh1MouseClicked

    private void cbx_loaiSP1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_loaiSP1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_loaiSP1ItemStateChanged

    private void cbx_ncc1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_ncc1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ncc1ItemStateChanged

    private void cbx_loaiSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_loaiSPItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            hienThiDanhSachSPTheoLoai();
        }
    }//GEN-LAST:event_cbx_loaiSPItemStateChanged

    private void cbx_nccItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_nccItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            hienThiDanhSachSPTheoNCC();
        }
    }//GEN-LAST:event_cbx_nccItemStateChanged

    private void cbx_ttItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_ttItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            hienThiDanhSachSPTheoTrangThai();
        }
    }//GEN-LAST:event_cbx_ttItemStateChanged

    private void btn_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timkiemMouseClicked
        // TODO add your handling code here:
        dtb.setRowCount(0);
        hienThiDanhSachSPTheoTenSP();
    }//GEN-LAST:event_btn_timkiemMouseClicked

    private void cbx_giaTienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_giaTienItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            int selectedIndex = cbx_giaTien.getSelectedIndex();
            if(selectedIndex==0)
            {
                gia=">= 0 AND DonGia <= 100000";
            }
            else if(selectedIndex == 1)
            {
                gia=">= 100000 AND DonGia <= 500000";
            }
            else if(selectedIndex == 2)
            {
                gia=">= 500000 AND DonGia <= 1000000";
            }
            else
            {
                gia=">= 1000000";
            }
            hienThiDanhSachSPTheoGia(gia);
        }
    }//GEN-LAST:event_cbx_giaTienItemStateChanged

    private void tb_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sanphamMouseClicked
        int numRows = tb_sanpham.getSelectedRow();

        String ma = String.valueOf(tb_sanpham.getValueAt(numRows, 0));
        Pojo.SanPham loadloai = SanPhamDAO.TimloaiSPTheoMa(ma);
        NhaCungCap loadTenNCC = NhaCungCapDAO.TimNCCSPTheoMa(ma);
        if(loadloai!=null)
        {
            cbx_loaiSP1.setSelectedItem((String)loadloai.getTenLoai());
        }
        if(loadTenNCC!=null)
        {
            cbx_ncc1.setSelectedItem((String)loadTenNCC.getTenNCC());
        }
        txt_maSP.setText(String.valueOf(tb_sanpham.getValueAt(numRows, 0)));
        txt_tenSP.setText(tb_sanpham.getValueAt(numRows, 2).toString());
        txt_donGia.setText(String.valueOf(tb_sanpham.getValueAt(numRows, 4)));

        txt_mau.setText(tb_sanpham.getValueAt(numRows, 3).toString());
        Pojo.SanPham sanpham= SanPhamDAO.loadSP(ma);
        lb_hinh.setIcon(ResizeImage(sanpham.getHinh()));
    }//GEN-LAST:event_tb_sanphamMouseClicked

    private void btn_themAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themAnhMouseClicked
        try {
            JFileChooser f = new JFileChooser(System.getProperty("user.dir") + "./Images/");
            f.setDialogTitle("Chọn Ảnh");
            f.showOpenDialog(null);
            File fileAnh = f.getSelectedFile();
            if (fileAnh != null) {
                if (fileAnh.getAbsolutePath().contains("./Images/")) {
                    srcAnh = fileAnh.getName();
                } else {
                    File dirAnh = new File("./Images/");
                    srcAnh = dirAnh.toURI().relativize(fileAnh.getCanonicalFile().toURI()).getPath();
                }
                // Nối đường dẫn tương đối đến thư mục Images/ vào phía trước tên file ảnh.
                srcAnh = "./Images/" + srcAnh;
                lb_hinhAnhSanPham.setIcon(ResizeImage1(srcAnh));
                chooseImg = true;
            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Đã xảy ra sự cố! Không thể tải ảnh lên", "Thông báo!", JOptionPane.DEFAULT_OPTION);
            return;
        }
    }//GEN-LAST:event_btn_themAnhMouseClicked

    private void btn_luu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luu1MouseClicked
        if( txt_maSP1.getText().isEmpty() && txt_tenSP1.getText().isEmpty() && txt_tenLoai1.getText().isEmpty() && txt_donGia1.getText().isEmpty() && txt_mau1.getText().isEmpty() && txt_ncc1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Cần nhập đầy đủ thông tin của sản phẩm!!!");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn thay đổi thông tin của sản phẩm không?","Thông báo", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            {
                String src=srcAnh;
               
                if(SanPhamDAO.UpdateSanPham(txt_maSP1.getText(), txt_tenSP1.getText(), txt_mau1.getText(), txt_donGia1.getText(),   src,(String)cbx_tt1.getSelectedItem() ))
                {
                    JOptionPane.showMessageDialog(this, "Sửa thông tin sản phẩm thành công");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Sửa thông tin sản phẩm thất bại");
                }
                System.out.println(src);
            }
        }
    }//GEN-LAST:event_btn_luu1MouseClicked

    private void cbx_tt1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_tt1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tt1ItemStateChanged

    private void btn_luu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_luu1ActionPerformed

    private ImageIcon ResizeImage1(String path)
    {
        if (path != null) {
        ImageIcon myImage = new ImageIcon(path);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lb_hinhAnhSanPham.getWidth(), lb_hinhAnhSanPham.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
        }
        return null;
    }
       
    private ImageIcon ResizeImage(String path)
    {
        if (path != null) {
        ImageIcon myImage = new ImageIcon(path);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lb_hinh.getWidth(), lb_hinh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chiTietSP;
    private javax.swing.JButton btn_loadlai;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_luu1;
    private javax.swing.JButton btn_themAnh;
    private javax.swing.JButton btn_themAnh1;
    private javax.swing.JButton btn_themSP;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cbx_giaTien;
    private javax.swing.JComboBox<String> cbx_loaiSP;
    private javax.swing.JComboBox<String> cbx_loaiSP1;
    private javax.swing.JComboBox<String> cbx_ncc;
    private javax.swing.JComboBox<String> cbx_ncc1;
    private javax.swing.JComboBox<String> cbx_tt;
    private javax.swing.JComboBox<String> cbx_tt1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_hinh;
    private javax.swing.JLabel lb_hinhAnhSanPham;
    private javax.swing.JTable tb_sanpham;
    private javax.swing.JTextField txt_donGia;
    private javax.swing.JTextField txt_donGia1;
    private javax.swing.JTextField txt_maSP;
    private javax.swing.JTextField txt_maSP1;
    private javax.swing.JTextField txt_mau;
    private javax.swing.JTextField txt_mau1;
    private javax.swing.JTextField txt_ncc1;
    private javax.swing.JTextField txt_tenLoai1;
    private javax.swing.JTextField txt_tenSP;
    private javax.swing.JTextField txt_tenSP1;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables

    private void hienThiDanhSachSP() {
        dtb.setRowCount(0);
        ArrayList<Pojo.SanPham> dssp = SanPhamDAO.layDanhSachSanPham(); 
        for(Pojo.SanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getSoLuong());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
           
            dtb.addRow(v);
        }
    }
    
    private void hienThiComboBoxLoaiSP() {
        ArrayList<Pojo.SanPham> dsloai = SanPhamDAO.layDanhSachLoaiSanPham(); 
        for(Pojo.SanPham sp: dsloai)
        {
            cbx_loaiSP.addItem(sp.getTenLoai());
            cbx_loaiSP1.addItem(sp.getTenLoai());
        }   
    }
    
    private void hienThiComboBoxChiTietSP(String data) {
        cbx_tt1.addItem("Đang kinh doanh");
        cbx_tt1.addItem("Ngừng kinh doanh");
        cbx_tt1.setSelectedItem(data);
    }
    
    private void hienThiComboBoxNhaCungCap() {
        ArrayList<NhaCungCap> dsncc = NhaCungCapDAO.layDanhSachNhaCungCap(); 
        for(NhaCungCap ncc: dsncc)
        {
            cbx_ncc.addItem(ncc.getTenNCC());
            cbx_ncc1.addItem(ncc.getTenNCC());
        }    
    }
    
     private void hienThiComboBoxTinhTrangSP() {
        cbx_tt.addItem("Đang kinh doanh");
        cbx_tt.addItem("Ngừng kinh doanh");
    }
    
    private void hienThiDanhSachSPTheoLoai() {
        dtb.setRowCount(0);
        ArrayList<Pojo.SanPham> dssp = SanPhamDAO.DSSPTheoLoai((String) cbx_loaiSP.getSelectedItem()); 
        for(Pojo.SanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private void hienThiDanhSachSPTheoTrangThai() {
        dtb.setRowCount(0);
        ArrayList<Pojo.SanPham> dssp = SanPhamDAO.DSSPTheoTrangThai((String) cbx_tt.getSelectedItem()); 
        for(Pojo.SanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private void hienThiDanhSachSPTheoNCC() {
        dtb.setRowCount(0);
        ArrayList<Pojo.SanPham> dssp = SanPhamDAO.DSSPTheoNCC((String) cbx_ncc.getSelectedItem()); 
        for(Pojo.SanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
     private void hienThiDanhSachSPTheoTenSP() {
        dtb.setRowCount(0);
        ArrayList<Pojo.SanPham> dssp = SanPhamDAO.DSSPTheoTen(txt_timKiem.getText()); 
        for(Pojo.SanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private void hienThi() {
        dtb.setRowCount(0);
        hienThiComboBoxLoaiSP();
        hienThiComboBoxNhaCungCap();
        hienThiComboBoxTinhTrangSP();
        hienThiDanhSachSP();
      
    }

    private void hienThiDanhSachSPTheoGia(String gia) {
        dtb.setRowCount(0);
        ArrayList<Pojo.SanPham> dssp = SanPhamDAO.DSSPTheoGia(gia); 
        for(Pojo.SanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
}


