/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DAO.NhaCungCapDAO;
import DAO.QLSanPhamDAO;
import Pojo.NhaCungCap;
import Pojo.QLSanPham;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Bach Long
 */
public class SanPham extends javax.swing.JPanel {

    /**
     * Creates new form SanPham
     */
     DefaultTableModel dtb = new DefaultTableModel();
    boolean chooseImg = false;
    String srcAnh = "./src/Images/";
    String anh;
    String gia;
    public SanPham() {
        initComponents();
        String [] tieuDe={"Mã sản phẩm","Loại sản phẩm","Tên sản phẩm","Màu sắc","Đơn giá","Nhà cung cấp","Trạng thái"};
        dtb.setColumnIdentifiers(tieuDe);
        tb_sanpham.setModel(dtb);
        hienThi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_maSP = new javax.swing.JTextField();
        txt_tenLoai = new javax.swing.JTextField();
        txt_tenSP = new javax.swing.JTextField();
        txt_mau = new javax.swing.JTextField();
        txt_donGia = new javax.swing.JTextField();
        txt_ncc = new javax.swing.JTextField();
        btn_themSP = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_chiTietSP = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lb_hinh = new javax.swing.JLabel();
        btn_loadlai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbx_loaiSP = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbx_ncc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbx_tt = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timkiem = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cbx_giaTien = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sanpham = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_maSP1 = new javax.swing.JTextField();
        txt_tenLoai1 = new javax.swing.JTextField();
        txt_tenSP1 = new javax.swing.JTextField();
        txt_donGia1 = new javax.swing.JTextField();
        txt_ncc1 = new javax.swing.JTextField();
        txt_mau1 = new javax.swing.JTextField();
        btn_themAnh = new javax.swing.JButton();
        btn_luu1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lb_hinhAnhSanPham = new javax.swing.JLabel();
        cbx_tt1 = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sản phẩm"));

        jLabel1.setText("Mã sản phẩm");

        jLabel2.setText("Tên loại");

        jLabel3.setText("Tên sản phẩm");

        jLabel4.setText("Màu");

        jLabel5.setText("Nhà cung cấp");

        jLabel6.setText("Đơn giá");

        btn_themSP.setBackground(new java.awt.Color(255, 204, 51));
        btn_themSP.setText("Thêm sản phẩm");
        btn_themSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themSPActionPerformed(evt);
            }
        });

        btn_luu.setBackground(new java.awt.Color(255, 204, 51));
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_chiTietSP.setBackground(new java.awt.Color(255, 204, 51));
        btn_chiTietSP.setText("Chi tiết sản phẩm");
        btn_chiTietSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_chiTietSPMouseClicked(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_hinh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_loadlai.setBackground(new java.awt.Color(255, 204, 51));
        btn_loadlai.setText("Load lại");
        btn_loadlai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loadlaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_maSP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mau, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_loadlai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_chiTietSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(btn_luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_themSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_themSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_luu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chiTietSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_loadlai))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txt_maSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(txt_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txt_tenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txt_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_mau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lọc sản phẩm"));

        jLabel7.setText("Loại sản phẩm:");

        cbx_loaiSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_loaiSPItemStateChanged(evt);
            }
        });

        jLabel8.setText("Nhà cung cấp:");

        cbx_ncc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_nccItemStateChanged(evt);
            }
        });

        jLabel9.setText("Trạng thái:");

        cbx_tt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_ttItemStateChanged(evt);
            }
        });

        jLabel10.setText("Tìm kiếm:");

        btn_timkiem.setText("Tìm");
        btn_timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_timkiemMouseClicked(evt);
            }
        });

        jLabel19.setText("Giá:");

        cbx_giaTien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0đ - 100.000đ", "100.000đ - 500.000đ", "500.000đ - 1.000.000đ", "< 1.000.000đ" }));
        cbx_giaTien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_giaTienItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbx_loaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel9)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel19)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbx_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_tt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_giaTien, 0, 364, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_loaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem)
                    .addComponent(cbx_giaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));

        tb_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_sanpham.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tb_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sanpham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin sản Phẩm", jPanel2);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("THÔNG TIN CHI TIẾT SẢN PHẨM");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel12.setText("Mã sản phẩm");

        jLabel13.setText("Tên loại");

        jLabel14.setText("Tên sản phẩm");

        jLabel15.setText("Đơn giá");

        jLabel16.setText("Nhà cung cấp");

        jLabel17.setText("Màu");

        txt_maSP1.setEnabled(false);

        txt_tenLoai1.setEnabled(false);

        txt_ncc1.setEnabled(false);

        btn_themAnh.setText("Chọn ảnh");
        btn_themAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themAnhMouseClicked(evt);
            }
        });

        btn_luu1.setText("LƯU THAY ĐỔI");
        btn_luu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_luu1MouseClicked(evt);
            }
        });

        jLabel18.setText("Trạng thái");

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_hinhAnhSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_hinhAnhSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbx_tt1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_tt1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_themAnh)
                .addGap(290, 290, 290))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_donGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ncc1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mau1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_maSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(btn_luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_maSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tenLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_donGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ncc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_mau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbx_tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_themAnh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_luu1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chi tiết sản phẩm", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chiTietSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chiTietSPMouseClicked
        // TODO add your handling code here:
        QLSanPham sp = QLSanPhamDAO.loadSP(txt_maSP.getText());
        String ma = String.valueOf(sp.getMaSP());
        String gia = String.valueOf(sp.getDonGia());
        txt_maSP1.setText(ma);
        txt_tenSP1.setText(sp.getTenSP());
        txt_tenLoai1.setText(sp.getTenLoai());
        txt_donGia1.setText(gia);
        txt_mau1.setText(sp.getMau());
        txt_ncc1.setText(sp.getTenNCC());
        lb_hinhAnhSanPham.setIcon(ResizeImage1(sp.getHinh()));
        anh = sp.getHinh();
        cbx_tt1.removeAllItems();
        hienThiComboBoxChiTietSP(sp.getTrangThai());
    }//GEN-LAST:event_btn_chiTietSPMouseClicked

    private void btn_loadlaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loadlaiMouseClicked
        // TODO add your handling code here:
        hienThi();
    }//GEN-LAST:event_btn_loadlaiMouseClicked

    private void cbx_loaiSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_loaiSPItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            hienThiDanhSachSPTheoLoai();
        }
    }//GEN-LAST:event_cbx_loaiSPItemStateChanged

    private void cbx_nccItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_nccItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            hienThiDanhSachSPTheoNCC();
        }
    }//GEN-LAST:event_cbx_nccItemStateChanged

    private void cbx_ttItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_ttItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            hienThiDanhSachSPTheoTrangThai();
        }
    }//GEN-LAST:event_cbx_ttItemStateChanged

    private void btn_timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_timkiemMouseClicked
        // TODO add your handling code here:
        dtb.setRowCount(0);
        hienThiDanhSachSPTheoTenSP();
    }//GEN-LAST:event_btn_timkiemMouseClicked

    private void cbx_giaTienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_giaTienItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            dtb.setRowCount(0);
            int selectedIndex = cbx_giaTien.getSelectedIndex();
            if(selectedIndex==0)
            {
                gia=">= 0 AND DonGia <= 100000";
            }
            else if(selectedIndex == 1)
            {
                gia=">= 100000 AND DonGia <= 500000";
            }
            else if(selectedIndex == 2)
            {
                gia=">= 500000 AND DonGia <= 1000000";
            }
            else
            {
                gia=">= 1000000";
            }
            hienThiDanhSachSPTheoGia(gia);
        }
    }//GEN-LAST:event_cbx_giaTienItemStateChanged

    private void tb_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sanphamMouseClicked
        int numRows = tb_sanpham.getSelectedRow();
        String ma = String.valueOf(tb_sanpham.getValueAt(numRows, 0));
        txt_maSP.setText(String.valueOf(tb_sanpham.getValueAt(numRows, 0)));
        txt_tenLoai.setText(tb_sanpham.getValueAt(numRows, 1).toString());
        txt_tenSP.setText(tb_sanpham.getValueAt(numRows, 2).toString());
        txt_donGia.setText(String.valueOf(tb_sanpham.getValueAt(numRows, 3)));
        txt_ncc.setText(tb_sanpham.getValueAt(numRows, 4).toString());
        txt_mau.setText(tb_sanpham.getValueAt(numRows, 5).toString());
        QLSanPham sanpham= QLSanPhamDAO.loadSP(ma);
        lb_hinh.setIcon(ResizeImage(sanpham.getHinh()));
    }//GEN-LAST:event_tb_sanphamMouseClicked

    private void btn_themAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themAnhMouseClicked
        try {
            JFileChooser f = new JFileChooser(System.getProperty("user.dir") + "./Images/");
            f.setDialogTitle("Chọn Ảnh");
            f.showOpenDialog(null);
            File fileAnh = f.getSelectedFile();
            if (fileAnh != null) {
                if (fileAnh.getAbsolutePath().contains("./Images/")) {
                    srcAnh = fileAnh.getName();
                } else {
                    File dirAnh = new File("./Images/");
                    srcAnh = dirAnh.toURI().relativize(fileAnh.getCanonicalFile().toURI()).getPath();
                }
                // Nối đường dẫn tương đối đến thư mục Images/ vào phía trước tên file ảnh.
                srcAnh = "./Images/" + srcAnh;
                lb_hinhAnhSanPham.setIcon(ResizeImage1(srcAnh));
                chooseImg = true;
            }

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Đã xảy ra sự cố! Không thể tải ảnh lên", "Thông báo!", JOptionPane.DEFAULT_OPTION);
            return;
        }
    }//GEN-LAST:event_btn_themAnhMouseClicked

    private void btn_luu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_luu1MouseClicked
        if( txt_maSP1.getText().isEmpty() && txt_tenSP1.getText().isEmpty() && txt_tenLoai1.getText().isEmpty() && txt_donGia1.getText().isEmpty() && txt_mau1.getText().isEmpty() && txt_ncc1.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Cần nhập đầy đủ thông tin của sản phẩm!!!");
        }
        else
        {
            if(JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn thay đổi thông tin của sản phẩm không?","Thông báo", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            {
                String src=srcAnh;
                if(QLSanPhamDAO.UpdateSanPham(txt_maSP1.getText(), txt_tenSP1.getText(), txt_mau1.getText(), txt_donGia1.getText(),   src,(String)cbx_tt1.getSelectedItem()))
                {
                    JOptionPane.showMessageDialog(this, "Sửa thông tin sản phẩm thành công");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Sửa thông tin sản phẩm thất bại");
                }
                System.out.println(src);
            }
        }
    }//GEN-LAST:event_btn_luu1MouseClicked

    private void cbx_tt1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_tt1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_tt1ItemStateChanged

    private void btn_themSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themSPActionPerformed
     ThemSanPham t = new ThemSanPham();
     t.setVisible(true);
    }//GEN-LAST:event_btn_themSPActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_luuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chiTietSP;
    private javax.swing.JButton btn_loadlai;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_luu1;
    private javax.swing.JButton btn_themAnh;
    private javax.swing.JButton btn_themSP;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cbx_giaTien;
    private javax.swing.JComboBox<String> cbx_loaiSP;
    private javax.swing.JComboBox<String> cbx_ncc;
    private javax.swing.JComboBox<String> cbx_tt;
    private javax.swing.JComboBox<String> cbx_tt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_hinh;
    private javax.swing.JLabel lb_hinhAnhSanPham;
    private javax.swing.JTable tb_sanpham;
    private javax.swing.JTextField txt_donGia;
    private javax.swing.JTextField txt_donGia1;
    private javax.swing.JTextField txt_maSP;
    private javax.swing.JTextField txt_maSP1;
    private javax.swing.JTextField txt_mau;
    private javax.swing.JTextField txt_mau1;
    private javax.swing.JTextField txt_ncc;
    private javax.swing.JTextField txt_ncc1;
    private javax.swing.JTextField txt_tenLoai;
    private javax.swing.JTextField txt_tenLoai1;
    private javax.swing.JTextField txt_tenSP;
    private javax.swing.JTextField txt_tenSP1;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables

    private void hienThiDanhSachSP() {
        dtb.setRowCount(0);
        ArrayList<QLSanPham> dssp = QLSanPhamDAO.layDanhSachSanPham(); 
        for(QLSanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private void hienThiComboBoxLoaiSP() {
        ArrayList<QLSanPham> dsloai = QLSanPhamDAO.layDanhSachLoaiSanPham(); 
        for(QLSanPham sp: dsloai)
        {
            cbx_loaiSP.addItem(sp.getTenLoai());
        }   
    }
    
    private void hienThiComboBoxChiTietSP(String data) {
        cbx_tt1.addItem("Đang kinh doanh");
        cbx_tt1.addItem("Ngừng kinh doanh");
        cbx_tt1.setSelectedItem(data);
    }
    
    private void hienThiComboBoxNhaCungCap() {
        ArrayList<NhaCungCap> dsncc = NhaCungCapDAO.layDanhSachNhaCungCap(); 
        for(NhaCungCap ncc: dsncc)
        {
            cbx_ncc.addItem(ncc.getTenNCC());
        }    
    }
    
     private void hienThiComboBoxTinhTrangSP() {    
        cbx_tt.addItem("Đang kinh doanh");
        cbx_tt.addItem("Ngừng kinh doanh");
    }
    
    private void hienThiDanhSachSPTheoLoai() {
        dtb.setRowCount(0);
        ArrayList<QLSanPham> dssp = QLSanPhamDAO.DSSPTheoLoai((String) cbx_loaiSP.getSelectedItem()); 
        for(QLSanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private void hienThiDanhSachSPTheoTrangThai() {
        dtb.setRowCount(0);
        ArrayList<QLSanPham> dssp = QLSanPhamDAO.DSSPTheoTrangThai((String) cbx_tt.getSelectedItem()); 
        for(QLSanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private void hienThiDanhSachSPTheoNCC() {
        dtb.setRowCount(0);
        ArrayList<QLSanPham> dssp = QLSanPhamDAO.DSSPTheoNCC((String) cbx_ncc.getSelectedItem()); 
        for(QLSanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
     private void hienThiDanhSachSPTheoTenSP() {
        dtb.setRowCount(0);
        ArrayList<QLSanPham> dssp = QLSanPhamDAO.DSSPTheoTen(txt_timKiem.getText()); 
        for(QLSanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private void hienThi() {
        dtb.setRowCount(0);
        hienThiComboBoxLoaiSP();
        hienThiComboBoxNhaCungCap();
        hienThiComboBoxTinhTrangSP();
        hienThiDanhSachSP();
    }

    private void hienThiDanhSachSPTheoGia(String gia) {
        dtb.setRowCount(0);
        ArrayList<QLSanPham> dssp = QLSanPhamDAO.DSSPTheoGia(gia); 
        for(QLSanPham sp: dssp) {
            Vector<Object> v = new Vector<>();
            v.add(sp.getMaSP());
            v.add(sp.getTenLoai());
            v.add(sp.getTenSP());
            v.add(sp.getMau());
            v.add(sp.getDonGia());
            v.add(sp.getTenNCC());
            v.add(sp.getTrangThai());
            dtb.addRow(v);
        }
    }
    
    private ImageIcon ResizeImage1(String path)
    {
        if (path != null) {
        ImageIcon myImage = new ImageIcon(path);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lb_hinhAnhSanPham.getWidth(), lb_hinhAnhSanPham.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
        }
        return null;
    }
    
    private ImageIcon ResizeImage(String path)
    {
        if (path != null) {
        ImageIcon myImage = new ImageIcon(path);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lb_hinh.getWidth(), lb_hinh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
        }
        return null;
    }

}
